/**
 * ═══════════════════════════════════════════════════════════════
 * Feature: B2B Registration (Wholesale Buyer Onboarding)
 * Story: b2b-registration
 * Traceability:
 *   TC-001, TC-002, TC-003, TC-004 → REQ-01 (Core registration lifecycle)
 *   TC-005..TC-010                → REQ-02 (Company Info fields)
 *   TC-011..TC-014                → REQ-03 (Contact Media conditional fields)
 *   TC-015..TC-018                → REQ-04 (Account Setup fields)
 *   TC-019..TC-021                → REQ-05 (Agreement checkboxes — 3, not 4, see correction)
 *   TC-022..TC-025                → REQ-06 (Email/username uniqueness)
 *   TC-026, TC-027                → REQ-07 (Admin Registration Applications grid)
 *   TC-028..TC-030                → REQ-08 (Admin activation lifecycle)
 *
 * Corrections applied from workflows/b2b-registration.verify.json (Stage 4 live exploration):
 *   - REQ-05: only 3 real checkboxes exist (ToS, Privacy Policy, 18+ Age) — "Wholesale
 *     Account Agreement" is display text, not a 4th checkbox.
 *   - REQ-07: "KD Registration Details" is not on the customer's own profile page — the
 *     confirmed real location is Admin → Advanced B2B/B2C → Registration Applications
 *     (/Admin/ErpRegistrationApplication/List).
 *   - Field validation (required-field + uniqueness checks) fires per-step at that step's
 *     "Next" transition, not deferred to the final Step 3 "Submit Application" click.
 *     Verified live for Step 1 fields (Company Name required, duplicate Email). Step 2's
 *     duplicate-username check (TC-024) is validated at the Step 2 → Step 3 transition,
 *     matching the field's own step per the wizard's documented structure in
 *     pages/register.page.ts — revisit if Stage 7 execution shows otherwise.
 *
 * Pre-emptive patterns injected (memory/healed-patterns.json, TRUSTED):
 *   - PAT-MODAL-002 (KDN welcome overlay) — baked into BasePage.dismissModals()
 *   - PAT-POPUP-003 (async multi-popup + don't-show-again) — baked into utils/helpers.ts
 *
 * Generated by: Agent 4 — Automation Codegen
 * Generated at: 2026-08-17T00:00:00.000Z
 * Source: workflows/b2b-registration.journey.json
 * Verified: workflows/b2b-registration.verify.json
 * ═══════════════════════════════════════════════════════════════
 */
import { test, expect, Browser, Page } from '@playwright/test';
import { RegisterPage, generateDynamicB2BRegistrationData, B2BRegistrationData } from '../../../pages/register.page';
import { LoginPage } from '../../../pages/login.page';
import { AdminCustomerDetailsPage } from '../../../pages/admin/admin-customer-details.page';
import { AdminRegistrationApplicationsPage } from '../../../pages/admin/admin-registration-applications.page';
import { ENV } from '../../../utils/env';
import { generateRandomString } from '../../../utils/helpers';

// ─── Shared Helpers ────────────────────────────────────────────────────────

/** Open a fresh admin-authenticated page reusing tests/.auth/admin.json (no re-login). */
async function withAdminPage<T>(browser: Browser, fn: (page: Page) => Promise<T>): Promise<T> {
  const context = await browser.newContext({ storageState: 'tests/.auth/admin.json' });
  const page = await context.newPage();
  try {
    return await fn(page);
  } finally {
    await context.close();
  }
}

/** Register a full account and wait for the result page. Returns the data used. */
async function registerFullAccount(page: Page, overrides: Partial<B2BRegistrationData> = {}): Promise<B2BRegistrationData> {
  const registerPage = new RegisterPage(page);
  const data = generateDynamicB2BRegistrationData(overrides);
  await registerPage.navigate();
  await registerPage.registerB2BUser(data);
  await registerPage.assertRegistrationSubmitted();
  return data;
}

test.describe('B2B Registration — Core Lifecycle @regression', () => {
  test('TC-001: Successful B2B registration creates inactive account, mapped to ERP application @REQ-01', async ({ page, browser }) => {
    const data = await registerFullAccount(page);

    await withAdminPage(browser, async (adminPage) => {
      const customerDetails = new AdminCustomerDetailsPage(adminPage);
      await customerDetails.searchOnly(data.email);
      await customerDetails.assertRoleContains(data.email, 'B2B Customer');

      const applications = new AdminRegistrationApplicationsPage(adminPage);
      await applications.navigate();
      await applications.assertGridDisplayed();
      await applications.assertApplicationDataVisible(data.companyName, { company: data.companyName });
    });
  });

  test('TC-002: Valid submission with alternate Type of Business and Contact Media combination @REQ-01', async ({ page }) => {
    await registerFullAccount(page, {
      typeOfBusiness: 'Retailer (Physical shop only)',
      preferredContactChannel: 'Messenger',
      messengerAccountName: `msgr_${generateRandomString(6)}`,
      messengerAccountLink: 'https://m.me/test-account',
      whatsAppNumber: undefined,
    });
  });

  test('TC-003: Missing required field (Company Name) blocks submission — no entity created @REQ-01', async ({ page, browser }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ companyName: '' });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
    await registerPage.assertValidationError('company name is required');

    await withAdminPage(browser, async (adminPage) => {
      const customerDetails = new AdminCustomerDetailsPage(adminPage);
      const rowCount = await customerDetails.getMatchingRowCount(data.email);
      expect(rowCount).toBe(0);
    });
  });

  test('TC-004: Rapid double-click on Submit does not create duplicate entities @REQ-01', async ({ page, browser }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData();
    await registerPage.navigate();
    await registerPage.fillCompleteB2BRegistrationForm(data);

    // Fire two rapid clicks synchronously — a real double-click race, not two sequential Playwright actions.
    await page.evaluate(() => {
      const btn = document.querySelector('#kd-register-submit') as HTMLButtonElement | null;
      btn?.click();
      btn?.click();
    });
    await registerPage.assertRegistrationSubmitted();

    await withAdminPage(browser, async (adminPage) => {
      const customerDetails = new AdminCustomerDetailsPage(adminPage);
      const rowCount = await customerDetails.getMatchingRowCount(data.email);
      expect(rowCount).toBe(1);
    });
  });
});

test.describe('B2B Registration — Company Info Fields @regression', () => {
  test('TC-005: All Company Info fields accepted across different Type of Business options @REQ-02', async ({ page }) => {
    const types: B2BRegistrationData['typeOfBusiness'][] = [
      'Wholesaler (Online page)',
      'Clinic / Pharmacy',
      'Reseller',
    ];
    for (const typeOfBusiness of types) {
      await test.step(`typeOfBusiness = ${typeOfBusiness}`, async () => {
        const registerPage = new RegisterPage(page);
        const data = generateDynamicB2BRegistrationData({ typeOfBusiness });
        await registerPage.navigate();
        await registerPage.fillStep1(data);
        const advanced = await registerPage.goToNextStep();
        expect(advanced).toBe(true);
      });
    }
  });

  test('TC-006: Empty Company Name blocks submission with validation error @REQ-02', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ companyName: '' });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
    await registerPage.assertValidationError('company name is required');
  });

  test('TC-007: Invalid email format blocks submission with validation error @REQ-02', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ email: 'not-an-email' });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
    await registerPage.assertValidationError();
  });

  test('TC-008: BD phone number — 11-digit accepted, 10-digit and 12-digit rejected @REQ-02', async ({ page }) => {
    const cases: { phone: string; label: string; expectAdvance: boolean }[] = [
      { phone: '01712345678', label: '11-digit (valid)', expectAdvance: true },
      { phone: '0171234567', label: '10-digit (too short)', expectAdvance: false },
      { phone: '017123456789', label: '12-digit (too long)', expectAdvance: false },
    ];
    for (const { phone, label, expectAdvance } of cases) {
      await test.step(label, async () => {
        const registerPage = new RegisterPage(page);
        const data = generateDynamicB2BRegistrationData({ phone });
        await registerPage.navigate();
        await registerPage.fillStep1(data);
        const advanced = await registerPage.goToNextStep();
        expect(advanced).toBe(expectAdvance);
      });
    }
  });

  test('TC-009: Special characters and Unicode in Company Name handled without breaking the form @REQ-02', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ companyName: `K-뷰티 & Co. <script>알럿</script> "Wholesale" #${generateRandomString(3)}` });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(true);
    await expect(registerPage.usernameInput).toBeVisible();
  });

  test('TC-010: Zip Code empty vs whitespace-only input — consistent handling @REQ-02', async ({ page }) => {
    const registerPage1 = new RegisterPage(page);
    const dataEmpty = generateDynamicB2BRegistrationData({ zipCode: '' });
    await registerPage1.navigate();
    await registerPage1.fillStep1(dataEmpty);
    const advancedWithEmpty = await registerPage1.goToNextStep();

    const registerPage2 = new RegisterPage(page);
    const dataWhitespace = generateDynamicB2BRegistrationData({ zipCode: '   ' });
    await registerPage2.navigate();
    await registerPage2.fillStep1(dataWhitespace);
    const advancedWithWhitespace = await registerPage2.goToNextStep();

    expect(advancedWithWhitespace).toBe(advancedWithEmpty);
  });
});

test.describe('B2B Registration — Contact Media Conditional Fields @regression', () => {
  test('TC-011: Selecting WhatsApp reveals required WhatsApp Number field, Messenger fields hidden @REQ-03', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    await registerPage.navigate();
    await registerPage.dismissModals();
    await registerPage.fillStep1({ preferredContactChannel: 'WhatsApp', whatsAppNumber: '01712345678' });
    await expect(registerPage.whatsAppNumberInput).toBeVisible();
    await expect(registerPage.messengerAccountNameInput).toBeHidden();
    await expect(registerPage.messengerAccountLinkInput).toBeHidden();
  });

  test('TC-012: Selecting Messenger reveals required Messenger fields, WhatsApp field hidden @REQ-03', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    await registerPage.navigate();
    await registerPage.dismissModals();
    await registerPage.fillStep1({
      preferredContactChannel: 'Messenger',
      messengerAccountName: `msgr_${generateRandomString(6)}`,
      messengerAccountLink: 'https://m.me/test-account',
    });
    await expect(registerPage.messengerAccountNameInput).toBeVisible();
    await expect(registerPage.messengerAccountLinkInput).toBeVisible();
    await expect(registerPage.whatsAppNumberInput).toBeHidden();
  });

  test('TC-013: Toggling Contact Media from WhatsApp to Messenger clears/hides the WhatsApp Number field @REQ-03', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    await registerPage.navigate();
    await registerPage.dismissModals();
    await registerPage.fillStep1({ preferredContactChannel: 'WhatsApp', whatsAppNumber: '01712345678' });
    await expect(registerPage.whatsAppNumberInput).toBeVisible();

    await registerPage.fillStep1({
      preferredContactChannel: 'Messenger',
      messengerAccountName: `msgr_${generateRandomString(6)}`,
      messengerAccountLink: 'https://m.me/test-account',
    });
    await expect(registerPage.whatsAppNumberInput).toBeHidden();
  });

  test('TC-014: WhatsApp selected but WhatsApp Number left blank blocks submission @REQ-03', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ preferredContactChannel: 'WhatsApp', whatsAppNumber: '' });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
  });
});

test.describe('B2B Registration — Account Setup Fields @regression', () => {
  test('TC-015: Valid Username, Password, Confirm Password, dropdown, and business textarea accepted @REQ-04', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData();
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    await registerPage.goToNextStep();
    await registerPage.fillStep2(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(true);
    await expect(registerPage.acceptTermsCheckbox).toBeVisible();
  });

  test('TC-016: Password and Confirm Password mismatch blocks submission @REQ-04', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ confirmPassword: 'SomethingElse@123' });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    await registerPage.goToNextStep();
    await registerPage.fillStep2(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
  });

  test('TC-017: Empty Password field blocks submission @REQ-04', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ password: '', confirmPassword: '' });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    await registerPage.goToNextStep();
    await registerPage.fillStep2(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
  });

  test('TC-018: Username containing special characters or spaces @REQ-04', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ username: `qa user ${generateRandomString(3)}!@#` });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    await registerPage.goToNextStep();
    await registerPage.fillStep2(data);
    // Either blocked with a field error, or normalized/accepted — assert the form doesn't crash either way.
    await registerPage.goToNextStep();
    const hasErrors = await registerPage.hasVisibleValidationErrors();
    const onStep3 = await registerPage.acceptTermsCheckbox.isVisible().catch(() => false);
    expect(hasErrors || onStep3).toBeTruthy();
  });
});

test.describe('B2B Registration — Agreement Checkboxes @regression', () => {
  test('TC-019: All 3 required checkboxes checked allows submission — Wholesale Agreement is display text, not a checkbox @REQ-05', async ({ page }) => {
    await registerFullAccount(page);
  });

  test('TC-020: Terms of Service unchecked blocks submission @REQ-05', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ acceptTermsOfService: false });
    await registerPage.navigate();
    await registerPage.fillCompleteB2BRegistrationForm(data);
    await registerPage.submitRegistration();
    await registerPage.assertValidationError();
  });

  test('TC-021: Only the 18+ Age confirmation unchecked blocks submission with specific error @REQ-05', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ ageConfirmed: false });
    await registerPage.navigate();
    await registerPage.fillCompleteB2BRegistrationForm(data);
    await registerPage.submitRegistration();
    await registerPage.assertValidationError();
  });
});

test.describe('B2B Registration — Email/Username Uniqueness @regression', () => {
  test('TC-022: Brand-new unique email and username pass the uniqueness check @REQ-06', async ({ page }) => {
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData();
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(true);
  });

  test('TC-023: Duplicate email (already-registered wholesale account) blocks submission with clear error @smoke @REQ-06', async ({ page }) => {
    test.skip(!ENV.CUSTOMER_EMAIL, 'ENV.CUSTOMER_EMAIL not configured — cannot test duplicate-email against a known active account.');
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ email: ENV.CUSTOMER_EMAIL });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
    await registerPage.assertValidationError('already exists');
  });

  test('TC-024: Duplicate username blocks submission with clear error @REQ-06', async ({ page }) => {
    const first = await registerFullAccount(page);

    const registerPage = new RegisterPage(page);
    const second = generateDynamicB2BRegistrationData({ username: first.username });
    await registerPage.navigate();
    await registerPage.fillStep1(second);
    await registerPage.goToNextStep();
    await registerPage.fillStep2(second);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
  });

  test('TC-025: Case-variant duplicate email blocks submission @REQ-06', async ({ page }) => {
    test.skip(!ENV.CUSTOMER_EMAIL, 'ENV.CUSTOMER_EMAIL not configured — cannot test case-variant duplicate email.');
    const caseVariantEmail = ENV.CUSTOMER_EMAIL[0].toUpperCase() + ENV.CUSTOMER_EMAIL.slice(1);
    const registerPage = new RegisterPage(page);
    const data = generateDynamicB2BRegistrationData({ email: caseVariantEmail });
    await registerPage.navigate();
    await registerPage.fillStep1(data);
    const advanced = await registerPage.goToNextStep();
    expect(advanced).toBe(false);
  });
});

test.describe('B2B Registration — Admin Registration Applications Grid @regression', () => {
  test('TC-026: Admin sees full submitted wholesale data in Advanced B2B/B2C > Registration Applications @REQ-07', async ({ page, browser }) => {
    const data = await registerFullAccount(page);

    await withAdminPage(browser, async (adminPage) => {
      const applications = new AdminRegistrationApplicationsPage(adminPage);
      await applications.navigate();
      await applications.assertGridDisplayed();
      await applications.assertApplicationDataVisible(data.companyName, { company: data.companyName });
    });
  });

  test('TC-027: Registration Applications list correctly handles no matching application, no crash @REQ-07', async ({ browser }) => {
    await withAdminPage(browser, async (adminPage) => {
      const applications = new AdminRegistrationApplicationsPage(adminPage);
      await applications.navigate();
      await applications.assertNoMatchHandledGracefully(`no-such-company-${generateRandomString(10)}`);
    });
  });
});

test.describe('B2B Registration — Admin Activation Lifecycle @smoke @regression', () => {
  test('TC-028: Admin activates account via Active flag + save — login enabled @REQ-08', async ({ page, browser }) => {
    const data = await registerFullAccount(page);

    await withAdminPage(browser, async (adminPage) => {
      const customerDetails = new AdminCustomerDetailsPage(adminPage);
      await customerDetails.searchAndOpenCustomer(data.email);
      await customerDetails.assertCustomerEditPageDisplayed();
      await customerDetails.approveAndActivateAccount();
      await customerDetails.assertSaveSuccess();
      await customerDetails.assertAccountIsActive();
    });

    const loginContext = await browser.newContext();
    const loginPage = new LoginPage(await loginContext.newPage());
    await loginPage.navigate();
    await loginPage.login(data.email, data.password);
    await expect(loginPage.page).not.toHaveURL(/\/login/, { timeout: 15000 });
    await loginContext.close();
  });

  test('TC-029: Login attempt before admin approval is blocked with inactive-account message @REQ-08', async ({ page }) => {
    const data = await registerFullAccount(page);

    const loginPage = new LoginPage(page);
    await loginPage.navigate();
    await loginPage.login(data.email, data.password);
    await expect(loginPage.page.locator('body')).toContainText(/account is not active/i, { timeout: 10000 });
    await expect(loginPage.page).toHaveURL(/\/login/);
  });

  test('TC-030: Admin deactivates a previously-active account — login blocked again @REQ-08', async ({ page, browser }) => {
    const data = await registerFullAccount(page);

    await withAdminPage(browser, async (adminPage) => {
      const customerDetails = new AdminCustomerDetailsPage(adminPage);
      await customerDetails.searchAndOpenCustomer(data.email);
      await customerDetails.approveAndActivateAccount();
      await customerDetails.assertAccountIsActive();

      await customerDetails.deactivateAccount();
      await customerDetails.assertAccountIsInactive();
    });

    const loginContext = await browser.newContext();
    const loginPage = new LoginPage(await loginContext.newPage());
    await loginPage.navigate();
    await loginPage.login(data.email, data.password);
    await expect(loginPage.page.locator('body')).toContainText(/account is not active/i, { timeout: 10000 });
    await loginContext.close();
  });
});
