/**
 * ═══════════════════════════════════════════════════════════════
 * Feature: Wishlist Management (Wholesale Customer Wishlist)
 * Story: wishlist-management
 * Traceability:
 *   TC-001, TC-003, TC-004        → REQ-01, REQ-02 (Dual navigation entry points)
 *   TC-002, TC-007                → REQ-01, REQ-03 (Unauthenticated access is blocked)
 *   TC-005, TC-006, TC-009        → REQ-03 (View Wishlist — single/multi/large item counts)
 *   TC-010, TC-011                → REQ-04 (Empty Wishlist State)
 *   TC-012, TC-013, TC-014, TC-015, TC-016 → REQ-05 (Add to Wishlist)
 *   TC-017, TC-018                → REQ-06 (Header count updates)
 *   TC-008                        → REQ-03 (DEFERRED — see below)
 *
 * Corrections applied from workflows/wishlist-management.verify.json (Stage 4 live exploration):
 *   - Sidebar link text is "Wishlist" (one word), not "Wish List" — fixed a broken
 *     pre-existing selector in utils/selectors.ts (myAccountWishlistSidebarLink).
 *   - Wishlist item card container is `article.wishlist-item`, not `.wishlist-content .product-item`
 *     (that class never existed on the page) — fixed in utils/selectors.ts (wishlistItemCard).
 *   - Unauthenticated `/wishlist` access redirects to exactly `/login`.
 *   - Add-to-wishlist requires a real/trusted click — a JS-dispatched click does not fire
 *     the site's AJAX handler. All clicks below use Playwright's native .click().
 *
 * ⚠️ Known discrepancy (memory/decisions.md D-011), NOT silently smoothed over:
 *   Re-adding an already-wishlisted product repeats the success message and increments
 *   the header count again, but does NOT duplicate the grid entry. TC-014 asserts this
 *   observed reality. Flagged to the product owner as an open intended-vs-bug question.
 *
 * ⚠️ TC-008 (discontinued/out-of-stock product rendering) is DEFERRED via test.fixme() —
 *   no such fixture exists in this catalog after searching 9 terms / 24+ products
 *   (workflows/wishlist-management.journey.md, J-12). Revisit if the owner supplies a SKU.
 *
 * Pre-emptive patterns injected (memory/healed-patterns.json, TRUSTED):
 *   - PAT-MODAL-002 (KDN welcome overlay) — baked into BasePage.dismissModals()
 *   - PAT-POPUP-003 (async multi-popup) — baked into utils/helpers.ts
 *   - PAT-STRICT-004 (header/footer/sidebar "Wishlist" text collides across 3 elements
 *     per page) — WishlistPage getters already scope by specific class + .first()
 *
 * Generated by: Agent 4 — Automation Codegen
 * Generated at: 2026-08-21T19:00:00.000Z
 * Source: workflows/wishlist-management.journey.json
 * Verified: workflows/wishlist-management.verify.json
 * ═══════════════════════════════════════════════════════════════
 */
import { test, expect, Browser, Page } from '@playwright/test';
import { WishlistPage } from '../../../pages/wishlist.page';
import { HomePage } from '../../../pages/home.page';
import { LoginPage } from '../../../pages/login.page';
import { waitForAjaxComplete } from '../../../utils/helpers';

const REFERENCE_PRODUCT_SLUG = '/cream';
const SECONDARY_PRODUCT_SLUG = '/gel-cream';

/** Open a fresh, fully unauthenticated context (no storageState) — used for guest-access tests. */
async function withGuestPage<T>(browser: Browser, fn: (page: Page) => Promise<T>): Promise<T> {
  const context = await browser.newContext({ storageState: { cookies: [], origins: [] } });
  const page = await context.newPage();
  try {
    return await fn(page);
  } finally {
    await context.close();
  }
}

// ─── J-01: Dual Navigation Entry Points ────────────────────────────────────────

test.describe('Wishlist Management — Navigation @regression', () => {
  test('TC-001: Customer navigates to Wishlist via My Account dashboard sidebar @REQ-01', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.navigateToWishlistViaSidebar();
    await wishlistPage.assertWishlistLoaded();
    await expect(page.locator('h1')).toHaveText('My account - Wishlist');
  });

  test('TC-003: Customer navigates to Wishlist via the header navbar wishlist icon @REQ-02', async ({ page }) => {
    const homePage = new HomePage(page);
    const wishlistPage = new WishlistPage(page);
    await homePage.navigate();
    await homePage.dismissModals();
    await wishlistPage.navigateToWishlistViaHeader();
    await wishlistPage.assertWishlistLoaded();
    await expect(page.locator('h1')).toHaveText('My account - Wishlist');
  });

  test('TC-004: Header wishlist icon navigates correctly from a non-home page @REQ-02', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await page.goto(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.dismissModals();
    await wishlistPage.navigateToWishlistViaHeader();
    await wishlistPage.assertWishlistLoaded();
    await expect(page.locator('h1')).toHaveText('My account - Wishlist');
  });
});

// ─── J-02: Unauthenticated Access Is Blocked ────────────────────────────────────

test.describe('Wishlist Management — Unauthenticated Access @regression', () => {
  test('TC-002: Unauthenticated user directly requesting the Wishlist URL is redirected to login @REQ-01', async ({ browser }) => {
    await withGuestPage(browser, async (page) => {
      const loginPage = new LoginPage(page);
      await page.goto('/wishlist');
      await loginPage.dismissModals();
      await expect(page).toHaveURL(/\/login/);
      await loginPage.assertLoginPageDisplayed();
    });
  });

  test('TC-007: Unauthenticated user cannot view populated Wishlist content directly via URL @REQ-03', async ({ browser }) => {
    await withGuestPage(browser, async (page) => {
      const wishlistPage = new WishlistPage(page);
      await page.goto('/wishlist');
      await wishlistPage.dismissModals();
      await expect(page).toHaveURL(/\/login/);
      await expect(wishlistPage.wishlistItemCards).toHaveCount(0);
    });
  });
});

// ─── J-03: Empty Wishlist State ────────────────────────────────────────────────

test.describe.serial('Wishlist Management — Empty State @regression', () => {
  test.beforeAll(async ({ browser }) => {
    const context = await browser.newContext({ storageState: 'tests/.auth/customer.json' });
    const page = await context.newPage();
    await new WishlistPage(page).removeAllItemsFromWishlist();
    await context.close();
  });

  test('TC-010: Empty wishlist displays "Your wishlist is empty." and a working "Browse products" button @REQ-04', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.navigate();
    await wishlistPage.dismissModals();
    await wishlistPage.assertEmptyWishlistState();
    await expect(wishlistPage.browseProductsButton).toBeVisible();
  });

  test('TC-011: "Browse products" button navigates to the home page @REQ-04', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.navigate();
    await wishlistPage.dismissModals();
    await wishlistPage.assertBrowseProductsButtonNavigates();
  });
});

// ─── J-04/J-05/J-06/J-08/J-09/J-10: Add / View / Remove Lifecycle ──────────────

test.describe.serial('Wishlist Management — Add to Wishlist @regression', () => {
  test.beforeAll(async ({ browser }) => {
    // Guarantee a clean starting state regardless of leftovers from a prior run
    // (e.g. a previous failed attempt whose own cleanup didn't get to run) — this
    // is what caused TC-012 to see count (2) instead of (1) in an earlier run.
    const context = await browser.newContext({ storageState: 'tests/.auth/customer.json' });
    const page = await context.newPage();
    await new WishlistPage(page).removeAllItemsFromWishlist();
    await context.close();
  });

  test.afterEach(async ({ page }) => {
    // Safety-net cleanup: always leave the shared account empty for the next test.
    await new WishlistPage(page).removeAllItemsFromWishlist();
  });

  test('TC-012: Clicking the wishlist button on a product card adds it with a success message @REQ-05', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.addProductToWishlistFromGridCard('cream', REFERENCE_PRODUCT_SLUG);
    await expect(await wishlistPage.getNotificationText()).toContain('The product has been added to your wishlist');
    await wishlistPage.assertHeaderWishlistCount(1);
  });

  test('TC-013: Clicking the wishlist button on the product detail page adds it with a success message @REQ-05', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.addProductToWishlistFromPDP(REFERENCE_PRODUCT_SLUG);
    await expect(await wishlistPage.getNotificationText()).toContain('The product has been added to your wishlist');
    await wishlistPage.assertHeaderWishlistCount(1);
  });

  test('TC-005: Wishlist page displays a product card with item details and a remove action @REQ-03', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.addProductToWishlistFromPDP(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.navigate();
    await wishlistPage.dismissModals();
    await wishlistPage.assertItemsDisplayed(1);
    await expect(wishlistPage.wishlistItemCards.first()).toContainText('Cream');
    await expect(wishlistPage.wishlistItemCards.first()).toContainText('$33.00');
    await expect(wishlistPage.removeItemButtons.first()).toBeVisible();
  });

  test('TC-006: Wishlist page displays one card per saved product for multiple items @REQ-03', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.addProductToWishlistFromPDP(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.addProductToWishlistFromPDP(SECONDARY_PRODUCT_SLUG);
    await wishlistPage.navigate();
    await wishlistPage.dismissModals();
    await wishlistPage.assertItemsDisplayed(2);
  });

  test('TC-017: Header wishlist count increments by 1 immediately after adding a new product @REQ-06', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.navigate();
    await wishlistPage.assertHeaderWishlistCount(0);
    await wishlistPage.addProductToWishlistFromPDP(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.assertHeaderWishlistCount(1);
  });

  test('TC-018: Header wishlist count decrements by 1 immediately after removing an item @REQ-06', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.addProductToWishlistFromPDP(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.assertHeaderWishlistCount(1);
    await wishlistPage.navigate();
    await wishlistPage.dismissModals();
    await wishlistPage.dismissModals(); // re-check immediately before click — see TC-009 note in wishlist.page.ts
    await wishlistPage.removeItemButtons.first().click({ force: true });
    await wishlistPage.assertHeaderWishlistCount(0);
  });

  test('TC-015: Rapid double-click on "Add to wishlist" does not create a duplicate entry @REQ-05', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await page.goto(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.dismissModals();
    await expect(wishlistPage.pdpWishlistButton).toBeVisible({ timeout: 10000 });
    // Re-dismiss immediately before clicking — see the identical note in
    // addProductToWishlistFromPDP: the auto-opening overlay can silently
    // reappear between the dismiss above and this click and absorb it.
    await wishlistPage.dismissModals();
    await Promise.all([
      wishlistPage.pdpWishlistButton.click({ force: true }),
      wishlistPage.pdpWishlistButton.click({ force: true }),
    ]);
    // Let the AJAX call(s) actually settle before navigating away — navigating too early
    // races the in-flight request and makes the wishlist page load before the add lands.
    await waitForAjaxComplete(page);
    await wishlistPage.navigate();
    await wishlistPage.dismissModals();
    await wishlistPage.assertItemsDisplayed(1);
  });

  test('TC-016: Add-to-wishlist AJAX request returns 200 and reflects in the DOM without a full page reload @REQ-05', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await page.goto(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.dismissModals();
    await wishlistPage.dismissModals();
    const [response] = await Promise.all([
      page.waitForResponse((res) => res.url().includes('/addproducttocart/details/') && res.request().method() === 'POST'),
      wishlistPage.pdpWishlistButton.click({ force: true }),
    ]);
    expect(response.status()).toBe(200);
    await wishlistPage.assertHeaderWishlistCount(1);
  });

  test('TC-014: Re-adding an already-wishlisted product repeats the success message and increments the header count, but does not duplicate the grid entry @REQ-05', async ({ page }) => {
    const wishlistPage = new WishlistPage(page);
    await wishlistPage.addProductToWishlistFromPDP(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.assertHeaderWishlistCount(1);

    // Re-add the SAME product — see memory/decisions.md D-011 for the confirmed, escalated discrepancy.
    await page.goto(REFERENCE_PRODUCT_SLUG);
    await wishlistPage.dismissModals();
    await wishlistPage.dismissModals();
    const [reAddResponse] = await Promise.all([
      page.waitForResponse((res) => res.url().includes('/addproducttocart/details/') && res.request().method() === 'POST'),
      wishlistPage.pdpWishlistButton.click({ force: true }),
    ]);
    expect(reAddResponse.status()).toBe(200);
    await expect(await wishlistPage.getNotificationText()).toContain('The product has been added to your wishlist');

    // Header count over-increments (D-011) ...
    await wishlistPage.assertHeaderWishlistCount(2);
    // ... but the grid stays deduplicated to exactly 1 card. Do NOT assert these two
    // numbers are equal — that is precisely the confirmed discrepancy under test here.
    await wishlistPage.navigate();
    await wishlistPage.dismissModals();
    await wishlistPage.assertItemsDisplayed(1);
  });
});

// ─── J-11: Large Wishlist (20+ Items) Boundary ─────────────────────────────────

test.describe.serial('Wishlist Management — Large Wishlist Boundary @regression', () => {
  const TWENTY_PLUS_SLUGS = [
    '/cream', '/gel-cream', '/eye-cream', '/eye-gel-cream', '/body-cream', '/hand-cream',
    '/toner-3', '/toner-pad',
    '/lip-mask', '/hair-mask', '/sheet-mask-2', '/wash-off-mask-2', '/clay-mask', '/mud-mask',
    '/serum', '/serum-mist', '/eye-serum', '/lip-serum', '/sun-serum', '/hair-serum',
    '/special-set',
  ];

  test.beforeAll(async ({ browser }) => {
    const context = await browser.newContext({ storageState: 'tests/.auth/customer.json' });
    const page = await context.newPage();
    await new WishlistPage(page).removeAllItemsFromWishlist();
    await context.close();
  });

  test.afterEach(async ({ page }) => {
    await new WishlistPage(page).removeAllItemsFromWishlist();
  });

  test('TC-009: Wishlist with a large number of items (20+) renders without breaking layout @REQ-03', async ({ page }) => {
    // 21 sequential navigate+add+ajax-wait cycles against a live site (~8-10s each,
    // observed) plus a 21-item afterEach cleanup — 120s measurably wasn't enough
    // (a real run timed out with only 16-18/21 items added). Budgeted generously.
    test.setTimeout(400_000);
    const wishlistPage = new WishlistPage(page);
    for (const slug of TWENTY_PLUS_SLUGS) {
      await wishlistPage.addProductToWishlistFromPDP(slug);
    }
    await wishlistPage.navigate();
    await wishlistPage.dismissModals();
    // The grid initially renders only 20 items (infinite-scroll pagination,
    // confirmed live — memory/decisions.md D-012) — load the rest before asserting.
    await wishlistPage.loadAllWishlistItems();
    await wishlistPage.assertItemsDisplayed(TWENTY_PLUS_SLUGS.length);
  });
});

// ─── J-12: Discontinued/Out-of-Stock Product Rendering — DEFERRED ─────────────

test.describe('Wishlist Management — Deferred @regression', () => {
  test.fixme(
    true,
    'TC-008: no discontinued/out-of-stock product fixture exists in this catalog — searched live across 9 terms / 24+ products (workflows/wishlist-management.journey.md, J-12). Revisit if the product owner supplies a specific SKU.'
  );
  test('TC-008: A discontinued/out-of-stock product in the wishlist renders without breaking the page @REQ-03', async () => {
    // Intentionally not implemented — see test.fixme() reason above.
  });
});
